# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'App.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

try:
    from PyQt4 import QtGui,QtCore
except ImportError:
    from PySide import QtGui,QtCore

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_BioNanoAnalyst(object):
    def setupUi(self, BioNanoAnalyst):
        BioNanoAnalyst.setObjectName(_fromUtf8("BioNanoAnalyst"))
        BioNanoAnalyst.resize(1310, 960)
        BioNanoAnalyst.setMinimumSize(QtCore.QSize(1310, 960))
        BioNanoAnalyst.setMaximumSize(QtCore.QSize(1310, 16777215))
        self.centralwidget = QtGui.QWidget(BioNanoAnalyst)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.mapping_status_frame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mapping_status_frame.sizePolicy().hasHeightForWidth())
        self.mapping_status_frame.setSizePolicy(sizePolicy)
        self.mapping_status_frame.setSizeIncrement(QtCore.QSize(0, 3))
        self.mapping_status_frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.mapping_status_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.mapping_status_frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.mapping_status_frame.setLineWidth(2)
        self.mapping_status_frame.setObjectName(_fromUtf8("mapping_status_frame"))
        self.gridLayout_7 = QtGui.QGridLayout(self.mapping_status_frame)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.ctg_frame = QtGui.QFrame(self.mapping_status_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctg_frame.sizePolicy().hasHeightForWidth())
        self.ctg_frame.setSizePolicy(sizePolicy)
        self.ctg_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.ctg_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.ctg_frame.setObjectName(_fromUtf8("ctg_frame"))
        self.gridLayout_8 = QtGui.QGridLayout(self.ctg_frame)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.fig_format_combox = QtGui.QComboBox(self.ctg_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fig_format_combox.sizePolicy().hasHeightForWidth())
        self.fig_format_combox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.fig_format_combox.setFont(font)
        self.fig_format_combox.setObjectName(_fromUtf8("fig_format_combox"))
        self.gridLayout_8.addWidget(self.fig_format_combox, 0, 5, 1, 1)
        self.label_9 = QtGui.QLabel(self.ctg_frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_8.addWidget(self.label_9, 0, 7, 1, 1)
        self.ctg_check_label = QtGui.QLabel(self.ctg_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctg_check_label.sizePolicy().hasHeightForWidth())
        self.ctg_check_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.ctg_check_label.setFont(font)
        self.ctg_check_label.setObjectName(_fromUtf8("ctg_check_label"))
        self.gridLayout_8.addWidget(self.ctg_check_label, 0, 0, 1, 1)
        self.ctg_check_combox = QtGui.QComboBox(self.ctg_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ctg_check_combox.sizePolicy().hasHeightForWidth())
        self.ctg_check_combox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.ctg_check_combox.setFont(font)
        self.ctg_check_combox.setObjectName(_fromUtf8("ctg_check_combox"))
        self.gridLayout_8.addWidget(self.ctg_check_combox, 0, 1, 1, 1)
        self.fig_save_bn = QtGui.QPushButton(self.ctg_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fig_save_bn.sizePolicy().hasHeightForWidth())
        self.fig_save_bn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.fig_save_bn.setFont(font)
        self.fig_save_bn.setObjectName(_fromUtf8("fig_save_bn"))
        self.gridLayout_8.addWidget(self.fig_save_bn, 0, 14, 1, 1)
        self.save_select_bn = QtGui.QPushButton(self.ctg_frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.save_select_bn.setFont(font)
        self.save_select_bn.setObjectName(_fromUtf8("save_select_bn"))
        self.gridLayout_8.addWidget(self.save_select_bn, 0, 9, 1, 1)
        self.save_input = QtGui.QLineEdit(self.ctg_frame)
        self.save_input.setObjectName(_fromUtf8("save_input"))
        self.gridLayout_8.addWidget(self.save_input, 0, 8, 1, 1)
        self.save_clear_bn = QtGui.QPushButton(self.ctg_frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.save_clear_bn.setFont(font)
        self.save_clear_bn.setObjectName(_fromUtf8("save_clear_bn"))
        self.gridLayout_8.addWidget(self.save_clear_bn, 0, 10, 1, 1)
        self.fig_format_label = QtGui.QLabel(self.ctg_frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.fig_format_label.setFont(font)
        self.fig_format_label.setObjectName(_fromUtf8("fig_format_label"))
        self.gridLayout_8.addWidget(self.fig_format_label, 0, 4, 1, 1)
        self.fig_save_label = QtGui.QLabel(self.ctg_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fig_save_label.sizePolicy().hasHeightForWidth())
        self.fig_save_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.fig_save_label.setFont(font)
        self.fig_save_label.setObjectName(_fromUtf8("fig_save_label"))
        self.gridLayout_8.addWidget(self.fig_save_label, 0, 3, 1, 1)
        self.save_all_bn = QtGui.QPushButton(self.ctg_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_all_bn.sizePolicy().hasHeightForWidth())
        self.save_all_bn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.save_all_bn.setFont(font)
        self.save_all_bn.setObjectName(_fromUtf8("save_all_bn"))
        self.gridLayout_8.addWidget(self.save_all_bn, 0, 16, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem, 0, 6, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem1, 0, 15, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem2, 0, 2, 1, 1)
        self.gridLayout_7.addWidget(self.ctg_frame, 0, 0, 1, 1)
        self.mapping_status_view = QtGui.QGraphicsView(self.mapping_status_frame)
        self.mapping_status_view.setObjectName(_fromUtf8("mapping_status_view"))
        self.gridLayout_7.addWidget(self.mapping_status_view, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.mapping_status_frame, 4, 0, 1, 3)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.mapping_titile = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mapping_titile.sizePolicy().hasHeightForWidth())
        self.mapping_titile.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.mapping_titile.setFont(font)
        self.mapping_titile.setObjectName(_fromUtf8("mapping_titile"))
        self.gridLayout.addWidget(self.mapping_titile, 3, 0, 1, 1)
        self.result_widget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.result_widget.sizePolicy().hasHeightForWidth())
        self.result_widget.setSizePolicy(sizePolicy)
        self.result_widget.setObjectName(_fromUtf8("result_widget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.result_widget)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.Stats = QtGui.QTabWidget(self.result_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Stats.sizePolicy().hasHeightForWidth())
        self.Stats.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.Stats.setFont(font)
        self.Stats.setObjectName(_fromUtf8("Stats"))
        self.workflow = QtGui.QWidget()
        self.workflow.setObjectName(_fromUtf8("workflow"))
        self.show_ref_bn = QtGui.QPushButton(self.workflow)
        self.show_ref_bn.setGeometry(QtCore.QRect(10, 52, 91, 31))
        self.show_ref_bn.setObjectName(_fromUtf8("show_ref_bn"))
        self.show_unqualified_bn = QtGui.QPushButton(self.workflow)
        self.show_unqualified_bn.setGeometry(QtCore.QRect(200, 20, 141, 31))
        self.show_unqualified_bn.setObjectName(_fromUtf8("show_unqualified_bn"))
        self.line = QtGui.QFrame(self.workflow)
        self.line.setGeometry(QtCore.QRect(100, 60, 61, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(self.workflow)
        self.line_2.setGeometry(QtCore.QRect(160, 40, 3, 61))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(self.workflow)
        self.line_3.setGeometry(QtCore.QRect(160, 30, 41, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.show_qualified_bn = QtGui.QPushButton(self.workflow)
        self.show_qualified_bn.setGeometry(QtCore.QRect(200, 82, 141, 31))
        self.show_qualified_bn.setObjectName(_fromUtf8("show_qualified_bn"))
        self.line_4 = QtGui.QFrame(self.workflow)
        self.line_4.setGeometry(QtCore.QRect(160, 90, 41, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.show_BN_bn = QtGui.QPushButton(self.workflow)
        self.show_BN_bn.setGeometry(QtCore.QRect(200, 140, 141, 31))
        self.show_BN_bn.setObjectName(_fromUtf8("show_BN_bn"))
        self.line_5 = QtGui.QFrame(self.workflow)
        self.line_5.setGeometry(QtCore.QRect(340, 90, 21, 20))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_6 = QtGui.QFrame(self.workflow)
        self.line_6.setGeometry(QtCore.QRect(340, 150, 21, 20))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.line_7 = QtGui.QFrame(self.workflow)
        self.line_7.setGeometry(QtCore.QRect(350, 100, 20, 61))
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.line_8 = QtGui.QFrame(self.workflow)
        self.line_8.setGeometry(QtCore.QRect(360, 120, 71, 16))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.line_9 = QtGui.QFrame(self.workflow)
        self.line_9.setGeometry(QtCore.QRect(420, 100, 20, 61))
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.line_10 = QtGui.QFrame(self.workflow)
        self.line_10.setGeometry(QtCore.QRect(430, 90, 31, 20))
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.line_11 = QtGui.QFrame(self.workflow)
        self.line_11.setGeometry(QtCore.QRect(430, 150, 31, 20))
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.show_unmapped_bn = QtGui.QPushButton(self.workflow)
        self.show_unmapped_bn.setGeometry(QtCore.QRect(460, 80, 131, 31))
        self.show_unmapped_bn.setObjectName(_fromUtf8("show_unmapped_bn"))
        self.show_mapped_bn = QtGui.QPushButton(self.workflow)
        self.show_mapped_bn.setGeometry(QtCore.QRect(460, 140, 131, 31))
        self.show_mapped_bn.setObjectName(_fromUtf8("show_mapped_bn"))
        self.line_12 = QtGui.QFrame(self.workflow)
        self.line_12.setGeometry(QtCore.QRect(510, 170, 20, 31))
        self.line_12.setFrameShape(QtGui.QFrame.VLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.line_13 = QtGui.QFrame(self.workflow)
        self.line_13.setGeometry(QtCore.QRect(230, 190, 411, 20))
        self.line_13.setFrameShape(QtGui.QFrame.HLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.line_14 = QtGui.QFrame(self.workflow)
        self.line_14.setGeometry(QtCore.QRect(220, 200, 16, 51))
        self.line_14.setFrameShape(QtGui.QFrame.VLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.line_15 = QtGui.QFrame(self.workflow)
        self.line_15.setGeometry(QtCore.QRect(300, 200, 16, 101))
        self.line_15.setFrameShape(QtGui.QFrame.VLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.line_16 = QtGui.QFrame(self.workflow)
        self.line_16.setGeometry(QtCore.QRect(410, 200, 16, 51))
        self.line_16.setFrameShape(QtGui.QFrame.VLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName(_fromUtf8("line_16"))
        self.line_17 = QtGui.QFrame(self.workflow)
        self.line_17.setGeometry(QtCore.QRect(540, 200, 16, 141))
        self.line_17.setFrameShape(QtGui.QFrame.VLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName(_fromUtf8("line_17"))
        self.line_18 = QtGui.QFrame(self.workflow)
        self.line_18.setGeometry(QtCore.QRect(630, 200, 16, 51))
        self.line_18.setFrameShape(QtGui.QFrame.VLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName(_fromUtf8("line_18"))
        self.show_perfect_bn = QtGui.QPushButton(self.workflow)
        self.show_perfect_bn.setGeometry(QtCore.QRect(150, 250, 151, 31))
        self.show_perfect_bn.setObjectName(_fromUtf8("show_perfect_bn"))
        self.show_rsp_bn = QtGui.QPushButton(self.workflow)
        self.show_rsp_bn.setGeometry(QtCore.QRect(174, 300, 331, 31))
        self.show_rsp_bn.setObjectName(_fromUtf8("show_rsp_bn"))
        self.show_pp_bn = QtGui.QPushButton(self.workflow)
        self.show_pp_bn.setGeometry(QtCore.QRect(310, 250, 231, 31))
        self.show_pp_bn.setObjectName(_fromUtf8("show_pp_bn"))
        self.show_both_bn = QtGui.QPushButton(self.workflow)
        self.show_both_bn.setGeometry(QtCore.QRect(480, 340, 151, 31))
        self.show_both_bn.setObjectName(_fromUtf8("show_both_bn"))
        self.show_missing_bn = QtGui.QPushButton(self.workflow)
        self.show_missing_bn.setGeometry(QtCore.QRect(590, 250, 101, 31))
        self.show_missing_bn.setObjectName(_fromUtf8("show_missing_bn"))
        self.label_2 = QtGui.QLabel(self.workflow)
        self.label_2.setGeometry(QtCore.QRect(110, 43, 46, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.workflow)
        self.label_3.setGeometry(QtCore.QRect(110, 80, 46, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.workflow)
        self.label_4.setGeometry(QtCore.QRect(150, 10, 46, 21))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.workflow)
        self.label_5.setGeometry(QtCore.QRect(145, 110, 51, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.workflow)
        self.label_6.setGeometry(QtCore.QRect(370, 110, 81, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.workflow)
        self.label_7.setGeometry(QtCore.QRect(370, 130, 61, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.line_19 = QtGui.QFrame(self.workflow)
        self.line_19.setGeometry(QtCore.QRect(590, 90, 41, 16))
        self.line_19.setFrameShape(QtGui.QFrame.HLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName(_fromUtf8("line_19"))
        self.line_20 = QtGui.QFrame(self.workflow)
        self.line_20.setGeometry(QtCore.QRect(620, 70, 20, 61))
        self.line_20.setFrameShape(QtGui.QFrame.VLine)
        self.line_20.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_20.setObjectName(_fromUtf8("line_20"))
        self.line_21 = QtGui.QFrame(self.workflow)
        self.line_21.setGeometry(QtCore.QRect(630, 60, 31, 20))
        self.line_21.setFrameShape(QtGui.QFrame.HLine)
        self.line_21.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_21.setObjectName(_fromUtf8("line_21"))
        self.line_22 = QtGui.QFrame(self.workflow)
        self.line_22.setGeometry(QtCore.QRect(630, 120, 31, 20))
        self.line_22.setFrameShape(QtGui.QFrame.HLine)
        self.line_22.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_22.setObjectName(_fromUtf8("line_22"))
        self.show_filtered_bn = QtGui.QPushButton(self.workflow)
        self.show_filtered_bn.setGeometry(QtCore.QRect(660, 120, 111, 31))
        self.show_filtered_bn.setObjectName(_fromUtf8("show_filtered_bn"))
        self.show_no_mapping_bn = QtGui.QPushButton(self.workflow)
        self.show_no_mapping_bn.setGeometry(QtCore.QRect(660, 50, 101, 31))
        self.show_no_mapping_bn.setObjectName(_fromUtf8("show_no_mapping_bn"))
        self.Stats.addTab(self.workflow, _fromUtf8(""))
        self.statistics = QtGui.QWidget()
        self.statistics.setObjectName(_fromUtf8("statistics"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.statistics)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.textBrowser = QtGui.QTextBrowser(self.statistics)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.horizontalLayout.addWidget(self.textBrowser)
        self.Stats.addTab(self.statistics, _fromUtf8(""))
        self.mapping = QtGui.QWidget()
        self.mapping.setObjectName(_fromUtf8("mapping"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.mapping)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.Stats.addTab(self.mapping, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.Stats)
        self.gridLayout.addWidget(self.result_widget, 1, 1, 2, 2)
        self.prepare_widget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prepare_widget.sizePolicy().hasHeightForWidth())
        self.prepare_widget.setSizePolicy(sizePolicy)
        self.prepare_widget.setMinimumSize(QtCore.QSize(0, 0))
        self.prepare_widget.setObjectName(_fromUtf8("prepare_widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.prepare_widget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.Ref_title = QtGui.QLabel(self.prepare_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ref_title.sizePolicy().hasHeightForWidth())
        self.Ref_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.Ref_title.setFont(font)
        self.Ref_title.setObjectName(_fromUtf8("Ref_title"))
        self.verticalLayout.addWidget(self.Ref_title)
        self.Ref_frame = QtGui.QFrame(self.prepare_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ref_frame.sizePolicy().hasHeightForWidth())
        self.Ref_frame.setSizePolicy(sizePolicy)
        self.Ref_frame.setMinimumSize(QtCore.QSize(470, 40))
        self.Ref_frame.setMaximumSize(QtCore.QSize(470, 16777215))
        self.Ref_frame.setAutoFillBackground(True)
        self.Ref_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Ref_frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.Ref_frame.setLineWidth(2)
        self.Ref_frame.setObjectName(_fromUtf8("Ref_frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.Ref_frame)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.ref_input = QtGui.QLineEdit(self.Ref_frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.ref_input.setFont(font)
        self.ref_input.setObjectName(_fromUtf8("ref_input"))
        self.gridLayout_2.addWidget(self.ref_input, 0, 0, 1, 1)
        self.ref_select_bn = QtGui.QPushButton(self.Ref_frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.ref_select_bn.setFont(font)
        self.ref_select_bn.setObjectName(_fromUtf8("ref_select_bn"))
        self.gridLayout_2.addWidget(self.ref_select_bn, 0, 1, 1, 1)
        self.ref_clear_bn = QtGui.QPushButton(self.Ref_frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.ref_clear_bn.setFont(font)
        self.ref_clear_bn.setObjectName(_fromUtf8("ref_clear_bn"))
        self.gridLayout_2.addWidget(self.ref_clear_bn, 0, 2, 1, 1)
        self.verticalLayout.addWidget(self.Ref_frame)
        self.raw_checkBox = QtGui.QCheckBox(self.prepare_widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.raw_checkBox.setFont(font)
        self.raw_checkBox.setObjectName(_fromUtf8("raw_checkBox"))
        self.verticalLayout.addWidget(self.raw_checkBox)
        self.raw_frame = QtGui.QFrame(self.prepare_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.raw_frame.sizePolicy().hasHeightForWidth())
        self.raw_frame.setSizePolicy(sizePolicy)
        self.raw_frame.setMinimumSize(QtCore.QSize(470, 140))
        self.raw_frame.setMaximumSize(QtCore.QSize(470, 16777215))
        self.raw_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.raw_frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.raw_frame.setLineWidth(2)
        self.raw_frame.setObjectName(_fromUtf8("raw_frame"))
        self.gridLayout_3 = QtGui.QGridLayout(self.raw_frame)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.raw_clear_bn = QtGui.QPushButton(self.raw_frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.raw_clear_bn.setFont(font)
        self.raw_clear_bn.setObjectName(_fromUtf8("raw_clear_bn"))
        self.gridLayout_3.addWidget(self.raw_clear_bn, 2, 6, 1, 1)
        self.enzyme_combox = QtGui.QComboBox(self.raw_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enzyme_combox.sizePolicy().hasHeightForWidth())
        self.enzyme_combox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.enzyme_combox.setFont(font)
        self.enzyme_combox.setObjectName(_fromUtf8("enzyme_combox"))
        self.gridLayout_3.addWidget(self.enzyme_combox, 0, 6, 1, 1)
        self.raw_select_bn = QtGui.QPushButton(self.raw_frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.raw_select_bn.setFont(font)
        self.raw_select_bn.setObjectName(_fromUtf8("raw_select_bn"))
        self.gridLayout_3.addWidget(self.raw_select_bn, 2, 5, 1, 1)
        self.raw_mapping_label = QtGui.QLabel(self.raw_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.raw_mapping_label.sizePolicy().hasHeightForWidth())
        self.raw_mapping_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.raw_mapping_label.setFont(font)
        self.raw_mapping_label.setObjectName(_fromUtf8("raw_mapping_label"))
        self.gridLayout_3.addWidget(self.raw_mapping_label, 3, 0, 1, 1)
        self.enzyme_label = QtGui.QLabel(self.raw_frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.enzyme_label.setFont(font)
        self.enzyme_label.setObjectName(_fromUtf8("enzyme_label"))
        self.gridLayout_3.addWidget(self.enzyme_label, 0, 0, 1, 1)
        self.raw_input = QtGui.QLineEdit(self.raw_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.raw_input.sizePolicy().hasHeightForWidth())
        self.raw_input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.raw_input.setFont(font)
        self.raw_input.setObjectName(_fromUtf8("raw_input"))
        self.gridLayout_3.addWidget(self.raw_input, 2, 0, 1, 5)
        self.raw_label = QtGui.QLabel(self.raw_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.raw_label.sizePolicy().hasHeightForWidth())
        self.raw_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.raw_label.setFont(font)
        self.raw_label.setObjectName(_fromUtf8("raw_label"))
        self.gridLayout_3.addWidget(self.raw_label, 1, 0, 1, 2)
        self.raw_start_bn = QtGui.QPushButton(self.raw_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.raw_start_bn.sizePolicy().hasHeightForWidth())
        self.raw_start_bn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.raw_start_bn.setFont(font)
        self.raw_start_bn.setObjectName(_fromUtf8("raw_start_bn"))
        self.gridLayout_3.addWidget(self.raw_start_bn, 3, 3, 1, 1)
        self.raw_settings_bn = QtGui.QPushButton(self.raw_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.raw_settings_bn.sizePolicy().hasHeightForWidth())
        self.raw_settings_bn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.raw_settings_bn.setFont(font)
        self.raw_settings_bn.setObjectName(_fromUtf8("raw_settings_bn"))
        self.gridLayout_3.addWidget(self.raw_settings_bn, 3, 1, 1, 1)
        self.frame = QtGui.QFrame(self.raw_frame)
        self.frame.setMinimumSize(QtCore.QSize(0, 18))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 20))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setLineWidth(2)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(10, 0, 71, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.raw_status_label = QtGui.QLabel(self.frame)
        self.raw_status_label.setGeometry(QtCore.QRect(80, 0, 101, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.raw_status_label.sizePolicy().hasHeightForWidth())
        self.raw_status_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.raw_status_label.setFont(font)
        self.raw_status_label.setObjectName(_fromUtf8("raw_status_label"))
        self.gridLayout_3.addWidget(self.frame, 3, 5, 1, 2)
        self.verticalLayout.addWidget(self.raw_frame)
        self.aligned_checkBox = QtGui.QCheckBox(self.prepare_widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.aligned_checkBox.setFont(font)
        self.aligned_checkBox.setObjectName(_fromUtf8("aligned_checkBox"))
        self.verticalLayout.addWidget(self.aligned_checkBox)
        self.aligned_frame = QtGui.QFrame(self.prepare_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aligned_frame.sizePolicy().hasHeightForWidth())
        self.aligned_frame.setSizePolicy(sizePolicy)
        self.aligned_frame.setMinimumSize(QtCore.QSize(470, 85))
        self.aligned_frame.setMaximumSize(QtCore.QSize(470, 16777215))
        self.aligned_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.aligned_frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.aligned_frame.setLineWidth(2)
        self.aligned_frame.setObjectName(_fromUtf8("aligned_frame"))
        self.gridLayout_4 = QtGui.QGridLayout(self.aligned_frame)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.qcmap_clear_bn = QtGui.QPushButton(self.aligned_frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.qcmap_clear_bn.setFont(font)
        self.qcmap_clear_bn.setObjectName(_fromUtf8("qcmap_clear_bn"))
        self.gridLayout_4.addWidget(self.qcmap_clear_bn, 2, 4, 1, 1)
        self.rcmap_input = QtGui.QLineEdit(self.aligned_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rcmap_input.sizePolicy().hasHeightForWidth())
        self.rcmap_input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.rcmap_input.setFont(font)
        self.rcmap_input.setObjectName(_fromUtf8("rcmap_input"))
        self.gridLayout_4.addWidget(self.rcmap_input, 1, 1, 1, 2)
        self.xmap_input = QtGui.QLineEdit(self.aligned_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xmap_input.sizePolicy().hasHeightForWidth())
        self.xmap_input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.xmap_input.setFont(font)
        self.xmap_input.setObjectName(_fromUtf8("xmap_input"))
        self.gridLayout_4.addWidget(self.xmap_input, 0, 1, 1, 2)
        self.xmap_select_bn = QtGui.QPushButton(self.aligned_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xmap_select_bn.sizePolicy().hasHeightForWidth())
        self.xmap_select_bn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.xmap_select_bn.setFont(font)
        self.xmap_select_bn.setObjectName(_fromUtf8("xmap_select_bn"))
        self.gridLayout_4.addWidget(self.xmap_select_bn, 0, 3, 1, 1)
        self.qcmap_input = QtGui.QLineEdit(self.aligned_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qcmap_input.sizePolicy().hasHeightForWidth())
        self.qcmap_input.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.qcmap_input.setFont(font)
        self.qcmap_input.setObjectName(_fromUtf8("qcmap_input"))
        self.gridLayout_4.addWidget(self.qcmap_input, 2, 1, 1, 2)
        self.qcmap_select_bn = QtGui.QPushButton(self.aligned_frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.qcmap_select_bn.setFont(font)
        self.qcmap_select_bn.setObjectName(_fromUtf8("qcmap_select_bn"))
        self.gridLayout_4.addWidget(self.qcmap_select_bn, 2, 3, 1, 1)
        self.qcmap_label = QtGui.QLabel(self.aligned_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qcmap_label.sizePolicy().hasHeightForWidth())
        self.qcmap_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.qcmap_label.setFont(font)
        self.qcmap_label.setObjectName(_fromUtf8("qcmap_label"))
        self.gridLayout_4.addWidget(self.qcmap_label, 2, 0, 1, 1)
        self.xmap_label = QtGui.QLabel(self.aligned_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xmap_label.sizePolicy().hasHeightForWidth())
        self.xmap_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.xmap_label.setFont(font)
        self.xmap_label.setObjectName(_fromUtf8("xmap_label"))
        self.gridLayout_4.addWidget(self.xmap_label, 0, 0, 1, 1)
        self.rcmap_clear_bn = QtGui.QPushButton(self.aligned_frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.rcmap_clear_bn.setFont(font)
        self.rcmap_clear_bn.setObjectName(_fromUtf8("rcmap_clear_bn"))
        self.gridLayout_4.addWidget(self.rcmap_clear_bn, 1, 4, 1, 1)
        self.rcmap_label = QtGui.QLabel(self.aligned_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rcmap_label.sizePolicy().hasHeightForWidth())
        self.rcmap_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.rcmap_label.setFont(font)
        self.rcmap_label.setObjectName(_fromUtf8("rcmap_label"))
        self.gridLayout_4.addWidget(self.rcmap_label, 1, 0, 1, 1)
        self.rcmap_select_bn = QtGui.QPushButton(self.aligned_frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.rcmap_select_bn.setFont(font)
        self.rcmap_select_bn.setObjectName(_fromUtf8("rcmap_select_bn"))
        self.gridLayout_4.addWidget(self.rcmap_select_bn, 1, 3, 1, 1)
        self.xmap_clear_bn = QtGui.QPushButton(self.aligned_frame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.xmap_clear_bn.setFont(font)
        self.xmap_clear_bn.setObjectName(_fromUtf8("xmap_clear_bn"))
        self.gridLayout_4.addWidget(self.xmap_clear_bn, 0, 4, 1, 1)
        self.verticalLayout.addWidget(self.aligned_frame)
        self.analyze_title = QtGui.QLabel(self.prepare_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analyze_title.sizePolicy().hasHeightForWidth())
        self.analyze_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.analyze_title.setFont(font)
        self.analyze_title.setObjectName(_fromUtf8("analyze_title"))
        self.verticalLayout.addWidget(self.analyze_title)
        self.analyse_frame = QtGui.QFrame(self.prepare_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analyse_frame.sizePolicy().hasHeightForWidth())
        self.analyse_frame.setSizePolicy(sizePolicy)
        self.analyse_frame.setMinimumSize(QtCore.QSize(470, 0))
        self.analyse_frame.setMaximumSize(QtCore.QSize(470, 16777215))
        self.analyse_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.analyse_frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.analyse_frame.setLineWidth(2)
        self.analyse_frame.setObjectName(_fromUtf8("analyse_frame"))
        self.gridLayout_5 = QtGui.QGridLayout(self.analyse_frame)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.analyse_bn = QtGui.QPushButton(self.analyse_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analyse_bn.sizePolicy().hasHeightForWidth())
        self.analyse_bn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        self.analyse_bn.setFont(font)
        self.analyse_bn.setObjectName(_fromUtf8("analyse_bn"))
        self.gridLayout_5.addWidget(self.analyse_bn, 0, 2, 1, 1)
        self.cs_label = QtGui.QLabel(self.analyse_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cs_label.sizePolicy().hasHeightForWidth())
        self.cs_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setBold(True)
        font.setWeight(75)
        self.cs_label.setFont(font)
        self.cs_label.setObjectName(_fromUtf8("cs_label"))
        self.gridLayout_5.addWidget(self.cs_label, 0, 0, 1, 1)
        self.cs_input = QtGui.QLineEdit(self.analyse_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cs_input.sizePolicy().hasHeightForWidth())
        self.cs_input.setSizePolicy(sizePolicy)
        self.cs_input.setMaximumSize(QtCore.QSize(50, 16777215))
        self.cs_input.setObjectName(_fromUtf8("cs_input"))
        self.gridLayout_5.addWidget(self.cs_input, 0, 1, 1, 1)
        self.frame_2 = QtGui.QFrame(self.analyse_frame)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 20))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 24))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setLineWidth(2)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label_10 = QtGui.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(10, 0, 71, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.analyse_status_label = QtGui.QLabel(self.frame_2)
        self.analyse_status_label.setGeometry(QtCore.QRect(80, 0, 91, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analyse_status_label.sizePolicy().hasHeightForWidth())
        self.analyse_status_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.analyse_status_label.setFont(font)
        self.analyse_status_label.setObjectName(_fromUtf8("analyse_status_label"))
        self.gridLayout_5.addWidget(self.frame_2, 0, 4, 1, 1)
        self.verticalLayout.addWidget(self.analyse_frame)
        self.gridLayout.addWidget(self.prepare_widget, 1, 0, 2, 1)
        BioNanoAnalyst.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(BioNanoAnalyst)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1310, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuNew = QtGui.QMenu(self.menubar)
        self.menuNew.setObjectName(_fromUtf8("menuNew"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        BioNanoAnalyst.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(BioNanoAnalyst)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        BioNanoAnalyst.setStatusBar(self.statusbar)
        self.actionNew = QtGui.QAction(BioNanoAnalyst)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionClose = QtGui.QAction(BioNanoAnalyst)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionAbout = QtGui.QAction(BioNanoAnalyst)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionManual = QtGui.QAction(BioNanoAnalyst)
        self.actionManual.setObjectName(_fromUtf8("actionManual"))
        self.actionFeedbacks = QtGui.QAction(BioNanoAnalyst)
        self.actionFeedbacks.setObjectName(_fromUtf8("actionFeedbacks"))
        self.menuNew.addAction(self.actionNew)
        self.menuNew.addAction(self.actionClose)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionManual)
        self.menuHelp.addAction(self.actionFeedbacks)
        self.menubar.addAction(self.menuNew.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(BioNanoAnalyst)
        self.Stats.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(BioNanoAnalyst)

    def retranslateUi(self, BioNanoAnalyst):
        BioNanoAnalyst.setWindowTitle(_translate("BioNanoAnalyst", "BioNanoAnalyst", None))
        self.label_9.setText(_translate("BioNanoAnalyst", "Output Location:", None))
        self.ctg_check_label.setText(_translate("BioNanoAnalyst", "Contig you want to check:", None))
        self.fig_save_bn.setText(_translate("BioNanoAnalyst", "Save current plot", None))
        self.save_select_bn.setText(_translate("BioNanoAnalyst", "Select", None))
        self.save_clear_bn.setText(_translate("BioNanoAnalyst", "Clear", None))
        self.fig_format_label.setText(_translate("BioNanoAnalyst", "Format", None))
        self.fig_save_label.setText(_translate("BioNanoAnalyst", "Save Plot: ", None))
        self.save_all_bn.setText(_translate("BioNanoAnalyst", "Save all plots", None))
        self.label.setText(_translate("BioNanoAnalyst", "BioNanoAnalyst", None))
        self.mapping_titile.setText(_translate("BioNanoAnalyst", "Mapping Plots", None))
        self.show_ref_bn.setText(_translate("BioNanoAnalyst", "Reference", None))
        self.show_unqualified_bn.setText(_translate("BioNanoAnalyst", "Unqualified contigs", None))
        self.show_qualified_bn.setText(_translate("BioNanoAnalyst", "Qualified contigs", None))
        self.show_BN_bn.setText(_translate("BioNanoAnalyst", "BioNano Data", None))
        self.show_unmapped_bn.setText(_translate("BioNanoAnalyst", "Unmapped contigs", None))
        self.show_mapped_bn.setText(_translate("BioNanoAnalyst", "Mapped contigs", None))
        self.show_perfect_bn.setText(_translate("BioNanoAnalyst", "Good mapping", None))
        self.show_rsp_bn.setText(_translate("BioNanoAnalyst", "Having restriction site number mapping problem", None))
        self.show_pp_bn.setText(_translate("BioNanoAnalyst", "Having position mapping problem", None))
        self.show_both_bn.setText(_translate("BioNanoAnalyst", "Having both problems", None))
        self.show_missing_bn.setText(_translate("BioNanoAnalyst", "Missing", None))
        self.label_2.setText(_translate("BioNanoAnalyst", "Enzyme", None))
        self.label_3.setText(_translate("BioNanoAnalyst", "Digestion", None))
        self.label_4.setText(_translate("BioNanoAnalyst", "Failed", None))
        self.label_5.setText(_translate("BioNanoAnalyst", "Passed", None))
        self.label_6.setText(_translate("BioNanoAnalyst", "Optical", None))
        self.label_7.setText(_translate("BioNanoAnalyst", "mapping", None))
        self.show_filtered_bn.setText(_translate("BioNanoAnalyst", "Filtered contigs", None))
        self.show_no_mapping_bn.setText(_translate("BioNanoAnalyst", "No mapping", None))
        self.Stats.setTabText(self.Stats.indexOf(self.workflow), _translate("BioNanoAnalyst", "Workflow", None))
        self.Stats.setTabText(self.Stats.indexOf(self.statistics), _translate("BioNanoAnalyst", "Statistics", None))
        self.Stats.setTabText(self.Stats.indexOf(self.mapping), _translate("BioNanoAnalyst", "Graph", None))
        self.Ref_title.setText(_translate("BioNanoAnalyst", "Reference from Assembly (fasta format)", None))
        self.ref_select_bn.setText(_translate("BioNanoAnalyst", "Select", None))
        self.ref_clear_bn.setText(_translate("BioNanoAnalyst", "Clear", None))
        self.raw_checkBox.setText(_translate("BioNanoAnalyst", "Option 1: Using Raw BioNano Data", None))
        self.raw_clear_bn.setText(_translate("BioNanoAnalyst", "Clear", None))
        self.raw_select_bn.setText(_translate("BioNanoAnalyst", "Select", None))
        self.raw_mapping_label.setText(_translate("BioNanoAnalyst", "Mapping:", None))
        self.enzyme_label.setText(_translate("BioNanoAnalyst", "Enzyme", None))
        self.raw_label.setText(_translate("BioNanoAnalyst", "Raw Data (bnx)", None))
        self.raw_start_bn.setText(_translate("BioNanoAnalyst", "Start", None))
        self.raw_settings_bn.setText(_translate("BioNanoAnalyst", "Settings", None))
        self.label_8.setText(_translate("BioNanoAnalyst", "Job Status:", None))
        self.raw_status_label.setText(_translate("BioNanoAnalyst", "No Job", None))
        self.aligned_checkBox.setText(_translate("BioNanoAnalyst", "Option 2: Using Aligned BioNano Data", None))
        self.qcmap_clear_bn.setText(_translate("BioNanoAnalyst", "Clear", None))
        self.xmap_select_bn.setText(_translate("BioNanoAnalyst", "Select", None))
        self.qcmap_select_bn.setText(_translate("BioNanoAnalyst", "Select", None))
        self.qcmap_label.setText(_translate("BioNanoAnalyst", "Qry cmap file", None))
        self.xmap_label.setText(_translate("BioNanoAnalyst", "Xmap file", None))
        self.rcmap_clear_bn.setText(_translate("BioNanoAnalyst", "Clear", None))
        self.rcmap_label.setText(_translate("BioNanoAnalyst", "Ref cmap file", None))
        self.rcmap_select_bn.setText(_translate("BioNanoAnalyst", "Select", None))
        self.xmap_clear_bn.setText(_translate("BioNanoAnalyst", "Clear", None))
        self.analyze_title.setText(_translate("BioNanoAnalyst", "Start to Analyze", None))
        self.analyse_bn.setText(_translate("BioNanoAnalyst", "Analyse", None))
        self.cs_label.setText(_translate("BioNanoAnalyst", "Confidence score", None))
        self.label_10.setText(_translate("BioNanoAnalyst", "Job Status:", None))
        self.analyse_status_label.setText(_translate("BioNanoAnalyst", "No Job", None))
        self.menuNew.setTitle(_translate("BioNanoAnalyst", "File", None))
        self.menuHelp.setTitle(_translate("BioNanoAnalyst", "Help", None))
        self.actionNew.setText(_translate("BioNanoAnalyst", "New", None))
        self.actionClose.setText(_translate("BioNanoAnalyst", "Close", None))
        self.actionAbout.setText(_translate("BioNanoAnalyst", "About", None))
        self.actionManual.setText(_translate("BioNanoAnalyst", "Manual", None))
        self.actionFeedbacks.setText(_translate("BioNanoAnalyst", "Feedbacks", None))
